### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by lrettig** [axic/keccak-wasm#3]
I can't get this WAST code to compile. I'm getting errors from both binaryen and wabt. I wrapped it in a basic `(module)` ([see gist](https://gist.github.com/lrettig/c96e5482503c5cd5cc4b64573cd6ca8f)).

```
> ~/eth/binaryen/bin/wasm-as keccak.wast
[parse exception: invalid wasm type]Fatal: error in parsing input
> ~/eth/wabt/bin/wat2wasm keccak.wast
keccak.wast:387:17: error: unexpected token $loop, expected ).
    (loop $done $loop
                ^^^^^
keccak.wast:401:3: error: unexpected token (, expected EOF.
  (func $keccak_pi
  ^

```

**Comment by axic** [comment]
You can use the derivative in https://github.com/ewasm/evm2wasm/blob/master/wasm/keccak.wast

There here should be updated to the latest syntax.

**Comment by lrettig** [comment]
Also needed to copy over `$memset` and `$memcpy` -- that compiled. Thanks.
